import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Copyright from "./components/Copyright";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OneLot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="onelot-logo.webp" type="image/png" />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        <hr className="w-full my-6 border-gray-200 sm:mx-auto lg:my-8" />
        <Copyright />
      </body>
    </html>
  );
}
